"""
Plantilla para scripts de migración Alembic.
Este archivo es usado por Alembic para generar nuevos archivos de versión.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1dacdd1b27be'
down_revision = 'e64d1ce1e4e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technicians',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('declared_specialty', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'full_name', name='uq_technician_shop_name'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_technicians_id'), 'technicians', ['id'], unique=False)
    op.create_index(op.f('ix_technicians_shop_id'), 'technicians', ['shop_id'], unique=False)
    op.add_column('tickets', sa.Column('technician_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tickets_technician_id'), 'tickets', ['technician_id'], unique=False)
    op.create_foreign_key('fk_tickets_technician_id', 'tickets', 'technicians', ['technician_id'], ['id'])

    # --- BACKFILL SCRIPT ---
    op.execute("""
        INSERT INTO technicians (id, shop_id, full_name, user_id, is_active, created_at, updated_at)
        SELECT gen_random_uuid(), shop_id, full_name, id, is_active, created_at, updated_at
        FROM users WHERE role = 'technician';
    """)
    op.execute("""
        UPDATE tickets
        SET technician_id = tech.id
        FROM technicians tech
        WHERE tickets.assigned_technician_id = tech.user_id;
    """)
    # --- END BACKFILL SCRIPT ---
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tickets_technician_id', 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_technician_id'), table_name='tickets')
    op.drop_column('tickets', 'technician_id')
    op.drop_index(op.f('ix_technicians_shop_id'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_id'), table_name='technicians')
    op.drop_table('technicians')
    # ### end Alembic commands ###
