"""
Plantilla para scripts de migración Alembic.
Este archivo es usado por Alembic para generar nuevos archivos de versión.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7aff55c099f7'
down_revision = 'd0c08a175bbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_items', sa.Column('item_type', sa.Enum('part', 'labor', 'other', name='item_type_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_items', 'item_type')
    # ### end Alembic commands ###
